### ISSUE TITLE
Unable to fetch a CSV file from a remote address

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/rest-api-component-v2#16]
Here is a scenario. There is a CSV file which we would like to get via the rest call and pass it on to an attachment for further processing in he flow.

While making a call an error is given:

```
{
  "errorCode": "ERR_HTTP_INVALID_HEADER_VALUE",
  "errorMessage": "Invalid value \"undefined\" for header \"Content-Length\"",
  "errorStack": "TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value \"undefined\" for header \"Content-Length\"\n    at ClientRequest.setHeader (_http_outgoing.js:561:3)\n    at new ClientRequest (_http_client.js:251:14)\n    at Object.request (http.js:50:10)\n    at /home/apprunner/lib/attachments.js:34:24\n    at new Promise (<anonymous>)\n    at uploadFile (/home/apprunner/lib/attachments.js:33:12)\n    at /home/apprunner/lib/attachments.js:64:12\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async TaskExec.module.exports.processMethod (/home/apprunner/lib/utils.js:171:14)"
}
```

**Comment by if0s** [comment]
Can't be reproduced
