### ISSUE TITLE
Investigate SQUIZ "Code: 500 Message: Internal Server Error"

### ISSUE THREAD

**Issue by erroneous0ne** [elasticio/rest-api-component-v2#44]
# Investigation

### Useful Links

- [Link](https://support.elastic.io/a/tickets/9127) to the SQUIZ ticket.
- [Link](https://elasticio.slack.com/archives/C6G1E4WB1/p1727166209145149) to the Slack conversation.

## Description

SQUIZ reported Code: 500 Message: Internal Server Error Body: {"message":"Error processing the request"} in the REST API v2 component. [Link](https://app.au.connect.squiz.cloud/c/66836edb92be87001255c777/w/66de93f19574d8001209523a/designer/66f22ac006fffa0012d49f6d/v/latest ) to the testing flow.

> The SQUIZ team found that Connect sends an **empty(blank)** body with the GET request which causes the issue.

Please see the logs:
```
[2024-09-24 11:12:06.883]: processMessage received
[2024-09-24 11:12:06.884]: Going to check if incoming message body is lightweight.
[2024-09-24 11:12:06.884]: No object id header so not lightweight.
[2024-09-24 11:12:06.885]: No object id header so not lightweight.
[2024-09-24 11:12:06.885]: Going to check if passthrough for step is lightweight. { stepId: 'step_1' }
[2024-09-24 11:12:06.889]: Checking rate limit parameters...
[2024-09-24 11:12:06.889]: Going to fetch secret
[2024-09-24 11:12:06.968]: Got secret
[2024-09-24 11:12:06.969]: Got request body
[2024-09-24 11:12:07.626]: Component error
[2024-09-24 11:12:07.626]: Response statusCode 500
[2024-09-24 11:12:07.627]: processMessage emit error
[2024-09-24 11:12:07.635]: Delay Between Calls is not set, process message without delay...
[2024-09-24 11:12:07.636]: processMessage emit end was called more than once
[2024-09-24 11:12:07.636]: processMessage emit end
```

Postman or Curl command works, see the GET endpoint and API key:

```
curl --location 'https://dxp.squiz.cloud/__dxp/au/file-storage/saw-2943/api/v2/file?source=/Integrations/DEV/Temp/' \
--header 'x-api-key: xxx'
```

## Component Version

2.0.15

## Actual Result

```
HTTP error: Code: 500 Message: Internal Server Error Body: {"message":"Error processing the request"}
    at checkErrors (/home/node/lib/utils.js:436:19)
    at async module.exports.processMethod (/home/node/lib/utils.js:175:14)
```

## Expected Result

200 OK

## Workaround(s)

Use the [Code](https://github.com/elasticio/code-component) component.

**Comment by erroneous0ne** [comment]
We decided that it would be better to present the REST API v3 component because the code itself is quite old and needs critical changes, also this will solve the problem with attachments.
